const { app, BrowserWindow, ipcMain, shell } = require('electron')
const path = require('path')
const fs = require('fs')
const os = require('os')
const { spawn, execFile } = require('child_process')
const https = require('https')
const http = require('http')

const isDev = !app.isPackaged

// ── Paths ─────────────────────────────────────────────────────────────────────
const DATA_DIR = path.join(os.homedir(), 'CraftServer')
const SERVERS_DIR = path.join(DATA_DIR, 'servers')
const CONFIG_FILE = path.join(DATA_DIR, 'config.json')
const PLAYIT_BIN = path.join(DATA_DIR, 'playit' + (process.platform === 'win32' ? '.exe' : ''))

;[DATA_DIR, SERVERS_DIR].forEach(d => { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }) })

const serverProcesses = {}
const playitProcesses = {}

// ── Helpers ───────────────────────────────────────────────────────────────────
function readConfig() {
  try { return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8')) } catch { return {} }
}
function writeConfig(cfg) { fs.writeFileSync(CONFIG_FILE, JSON.stringify(cfg, null, 2)) }

function readServers() {
  try { return JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'servers.json'), 'utf8')) } catch { return [] }
}
function writeServers(s) { fs.writeFileSync(path.join(DATA_DIR, 'servers.json'), JSON.stringify(s, null, 2)) }

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith('https') ? https : http
    mod.get(url, { headers: { 'User-Agent': 'CraftServer/0.1.0' } }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location)
        return fetchJson(res.headers.location).then(resolve).catch(reject)
      let data = ''
      res.on('data', c => { data += c })
      res.on('end', () => { try { resolve(JSON.parse(data)) } catch { reject(new Error('Invalid JSON')) } })
    }).on('error', reject)
  })
}

function downloadFile(url, dest, onProgress) {
  return new Promise((resolve, reject) => {
    const doDownload = (u) => {
      const mod = u.startsWith('https') ? https : http
      mod.get(u, { headers: { 'User-Agent': 'CraftServer/0.1.0' } }, res => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location)
          return doDownload(res.headers.location)
        const total = parseInt(res.headers['content-length'] || '0', 10)
        let received = 0
        const file = fs.createWriteStream(dest)
        res.on('data', chunk => {
          received += chunk.length
          if (onProgress && total) onProgress(Math.round((received / total) * 100))
        })
        res.pipe(file)
        file.on('finish', () => file.close(resolve))
        file.on('error', err => { fs.unlink(dest, () => {}); reject(err) })
      }).on('error', reject)
    }
    doDownload(url)
  })
}

// ── server.properties ─────────────────────────────────────────────────────────
function parseServerProperties(content) {
  const props = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const val = trimmed.slice(eq + 1).trim()
    if (val === 'true') props[key] = true
    else if (val === 'false') props[key] = false
    else if (!isNaN(val) && val !== '') props[key] = Number(val)
    else props[key] = val
  }
  return props
}

function stringifyServerProperties(props) {
  const lines = ['# Generated by CraftServer', '']
  for (const [k, v] of Object.entries(props)) {
    lines.push(`${k}=${v}`)
  }
  return lines.join('\n') + '\n'
}

ipcMain.handle('get-server-properties', (_, serverId) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return null
  const file = path.join(server.dir, 'server.properties')
  if (!fs.existsSync(file)) return null
  return parseServerProperties(fs.readFileSync(file, 'utf8'))
})

ipcMain.handle('set-server-properties', (_, { serverId, props }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false }
  const file = path.join(server.dir, 'server.properties')
  const existing = fs.existsSync(file) ? parseServerProperties(fs.readFileSync(file, 'utf8')) : {}
  const merged = { ...existing, ...props }
  fs.writeFileSync(file, stringifyServerProperties(merged))
  return { ok: true }
})

// ── Whitelist ─────────────────────────────────────────────────────────────────
ipcMain.handle('get-whitelist', (_, serverId) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return []
  const file = path.join(server.dir, 'whitelist.json')
  try { return JSON.parse(fs.readFileSync(file, 'utf8')) } catch { return [] }
})

ipcMain.handle('add-whitelist', async (_, { serverId, username }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false, error: 'Servidor não encontrado' }

  // Fetch UUID from Mojang API
  let uuid = '00000000-0000-0000-0000-000000000000'
  try {
    const data = await fetchJson(`https://api.mojang.com/users/profiles/minecraft/${username}`)
    if (data.id) {
      const raw = data.id
      uuid = `${raw.slice(0,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}-${raw.slice(16,20)}-${raw.slice(20)}`
    }
  } catch {
    // Offline mode: generate a deterministic offline UUID
    uuid = `OfflinePlayer:${username}`
  }

  const file = path.join(server.dir, 'whitelist.json')
  let list = []
  try { list = JSON.parse(fs.readFileSync(file, 'utf8')) } catch {}
  if (list.some(e => e.name.toLowerCase() === username.toLowerCase()))
    return { ok: false, error: 'Jogador já está na whitelist' }

  list.push({ uuid, name: username })
  fs.writeFileSync(file, JSON.stringify(list, null, 2))
  return { ok: true, entry: { uuid, name: username } }
})

ipcMain.handle('remove-whitelist', (_, { serverId, name }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false }
  const file = path.join(server.dir, 'whitelist.json')
  try {
    const list = JSON.parse(fs.readFileSync(file, 'utf8')).filter(e => e.name !== name)
    fs.writeFileSync(file, JSON.stringify(list, null, 2))
    return { ok: true }
  } catch { return { ok: false } }
})

// ── Versions ──────────────────────────────────────────────────────────────────
ipcMain.handle('get-versions', async (_, type) => {
  try {
    if (type === 'paper') {
      const d = await fetchJson('https://api.papermc.io/v2/projects/paper')
      return d.versions.reverse()
    }
    if (type === 'purpur') {
      const d = await fetchJson('https://api.purpurmc.org/v2/purpur')
      return d.versions.reverse()
    }
    if (type === 'fabric') {
      const d = await fetchJson('https://meta.fabricmc.net/v2/versions/game')
      return d.filter(v => v.stable).map(v => v.version)
    }
    if (type === 'bedrock' || type === 'hybrid') {
      // PowerNukkit — latest release tags from GitHub
      const releases = await fetchJson('https://api.github.com/repos/PowerNukkit/PowerNukkit/releases?per_page=10')
      return releases.map(r => r.tag_name.replace(/^v/, ''))
    }
    // vanilla
    const d = await fetchJson('https://launchermeta.mojang.com/mc/game/version_manifest.json')
    return d.versions.filter(v => v.type === 'release').map(v => v.id)
  } catch { return [] }
})

// ── Create server ─────────────────────────────────────────────────────────────
ipcMain.handle('create-server', async (event, opts) => {
  const { name, type, version, ram, port, plugins: selectedPlugins, offlineMode = false } = opts
  const id = Date.now().toString()
  const serverDir = path.join(SERVERS_DIR, id)
  fs.mkdirSync(serverDir, { recursive: true })
  fs.mkdirSync(path.join(serverDir, 'plugins'), { recursive: true })

  const send = msg => event.sender.send('create-progress', { id, msg })

  try {
    send(`Baixando ${type} ${version}...`)
    const jarPath = path.join(serverDir, 'server.jar')
    const jarUrl = await getJarUrl(type, version)
    await downloadFile(jarUrl, jarPath, pct => send(`Download: ${pct}%`))

    send('Configurando servidor...')
    fs.writeFileSync(path.join(serverDir, 'eula.txt'), 'eula=true\n')

    const isJava = type !== 'bedrock'
    if (isJava) {
      fs.writeFileSync(path.join(serverDir, 'server.properties'), buildServerProperties(port, name, offlineMode))
      fs.writeFileSync(path.join(serverDir, 'whitelist.json'), '[]')
    }

    // Hybrid: also install Geyser + Floodgate
    if (type === 'hybrid') {
      send('Baixando GeyserMC (ponte Java↔Bedrock)...')
      await downloadFile(
        'https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot',
        path.join(serverDir, 'plugins', 'Geyser-Spigot.jar')
      ).catch(() => send('Aviso: falha ao baixar Geyser, instale manualmente'))

      send('Baixando Floodgate...')
      await downloadFile(
        'https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot',
        path.join(serverDir, 'plugins', 'Floodgate-Spigot.jar')
      ).catch(() => send('Aviso: falha ao baixar Floodgate, instale manualmente'))
    }

    if (selectedPlugins && selectedPlugins.length > 0) {
      send('Instalando plugins...')
      for (const plugin of selectedPlugins) {
        send(`Instalando ${plugin.name}...`)
        try {
          await downloadFile(plugin.url, path.join(serverDir, 'plugins', plugin.filename))
        } catch { send(`Aviso: falha ao instalar ${plugin.name}`) }
      }
    }

    // Offline mode: generate AuthMe + SkinsRestorer configs pre-configured
    if (offlineMode) {
      send('Configurando modo offline (AuthMe + SkinsRestorer)...')

      const authmeDir = path.join(serverDir, 'plugins', 'AuthMe')
      fs.mkdirSync(authmeDir, { recursive: true })
      fs.writeFileSync(path.join(authmeDir, 'config.yml'), buildAuthMeConfig())

      const skinsDir = path.join(serverDir, 'plugins', 'SkinsRestorer')
      fs.mkdirSync(skinsDir, { recursive: true })
      fs.writeFileSync(path.join(skinsDir, 'config.yml'), buildSkinsRestorerConfig())
    }

    const server = { id, name, type, version, ram, port, dir: serverDir, createdAt: Date.now(), playit: false }
    const servers = readServers()
    servers.push(server)
    writeServers(servers)

    send('Servidor criado com sucesso!')
    return { ok: true, server }
  } catch (e) {
    return { ok: false, error: e.message }
  }
})

async function getJarUrl(type, version) {
  if (type === 'paper' || type === 'hybrid') {
    const builds = await fetchJson(`https://api.papermc.io/v2/projects/paper/versions/${version}/builds`)
    const build = builds.builds[builds.builds.length - 1].build
    return `https://api.papermc.io/v2/projects/paper/versions/${version}/builds/${build}/downloads/paper-${version}-${build}.jar`
  }
  if (type === 'purpur') {
    return `https://api.purpurmc.org/v2/purpur/${version}/latest/download`
  }
  if (type === 'vanilla') {
    const manifest = await fetchJson('https://launchermeta.mojang.com/mc/game/version_manifest.json')
    const entry = manifest.versions.find(v => v.id === version)
    const vdata = await fetchJson(entry.url)
    return vdata.downloads.server.url
  }
  if (type === 'fabric') {
    const loaders = await fetchJson(`https://meta.fabricmc.net/v2/versions/loader/${version}`)
    const lv = loaders[0].loader.version
    const installer = await fetchJson('https://meta.fabricmc.net/v2/versions/installer')
    const iv = installer[0].version
    return `https://meta.fabricmc.net/v2/versions/loader/${version}/${lv}/${iv}/server/jar`
  }
  if (type === 'bedrock') {
    // PowerNukkit — Bedrock protocol, runs on Java (Mac/Win/Linux)
    const tag = version.startsWith('v') ? version : `v${version}`
    const releases = await fetchJson('https://api.github.com/repos/PowerNukkit/PowerNukkit/releases?per_page=20')
    const release = releases.find(r => r.tag_name === tag || r.tag_name === version) || releases[0]
    const asset = release.assets.find(a => a.name.endsWith('.jar') && !a.name.includes('sources') && !a.name.includes('javadoc'))
    if (!asset) throw new Error('JAR do PowerNukkit não encontrado')
    return asset.browser_download_url
  }
  throw new Error(`Tipo desconhecido: ${type}`)
}

function buildServerProperties(port, name, offlineMode = false) {
  return [
    `server-port=${port}`,
    `motd=${name} - via CraftServer`,
    `online-mode=${offlineMode ? 'false' : 'true'}`,
    'white-list=false',
    'max-players=20',
    'gamemode=survival',
    'difficulty=normal',
    'pvp=true',
    'spawn-monsters=true',
    'spawn-animals=true',
    'spawn-npcs=true',
    'allow-flight=false',
    'spawn-protection=16',
    'view-distance=10',
    'simulation-distance=10',
    'level-name=world',
    'level-seed=',
    'server-ip=',
    'network-compression-threshold=256',
    'max-tick-time=60000',
  ].join('\n') + '\n'
}

function buildAuthMeConfig() {
  return `# AuthMe config — generated by CraftServer (offline mode)
DataSource:
  backend: SQLITE

settings:
  sessions:
    sessionLength: 0
    sessions: true

  registration:
    enabled: true
    force: true
    messageInterval: 20
    freeNameField: true

  restrictions:
    allowedNicknames: '^[a-zA-Z0-9_]{2,16}$'
    kickNonRegistered: false

  security:
    passwordMinLength: 4
    passwordMaxLength: 30

  email:
    smtp: ''
    senderEmail: ''

Premium:
  autoLogin: true
  checkPremiumAtStartup: true

GroupOptions:
  UnregisteredPlayerGroup: ''

# CraftServer: premium players (original game) auto-login via Mojang API.
# Cracked players must /register <password> once, then /login each session.
`
}

function buildSkinsRestorerConfig() {
  return `# SkinsRestorer config — generated by CraftServer (offline mode)
SkinRestorer:
  skinWithoutPerm: false
  StorageType: FILE
  AskProxyForSkins: false
  PipelineTimeout: 5
  WaitBeforeFetching: 2
  # Offline mode: SkinsRestorer fetches skins from Mojang even in offline servers.
  # Players keep their skin regardless of online-mode setting.
`
}

// ── Start / Stop ──────────────────────────────────────────────────────────────
ipcMain.handle('start-server', async (event, id) => {
  if (serverProcesses[id]) return { ok: false, error: 'Servidor já está rodando' }
  const servers = readServers()
  const server = servers.find(s => s.id === id)
  if (!server) return { ok: false, error: 'Servidor não encontrado' }

  const javaCmd = await findJava()
  if (!javaCmd) return { ok: false, error: 'Java não encontrado. Instale Java 17+ em adoptium.net' }

  const ramArg = `${server.ram}M`
  const proc = spawn(javaCmd, [`-Xmx${ramArg}`, `-Xms${ramArg}`, '-jar', 'server.jar', 'nogui'], {
    cwd: server.dir,
    stdio: ['pipe', 'pipe', 'pipe'],
  })
  serverProcesses[id] = proc

  proc.stdout.on('data', d => event.sender.send('server-log', { id, line: d.toString() }))
  proc.stderr.on('data', d => event.sender.send('server-log', { id, line: d.toString() }))
  proc.on('close', code => {
    delete serverProcesses[id]
    event.sender.send('server-stopped', { id, code })
  })
  return { ok: true }
})

ipcMain.handle('stop-server', async (_, id) => {
  const proc = serverProcesses[id]
  if (!proc) return { ok: false }
  proc.stdin.write('stop\n')
  setTimeout(() => { if (serverProcesses[id]) proc.kill() }, 10000)
  return { ok: true }
})

ipcMain.handle('send-command', (_, { id, command }) => {
  const proc = serverProcesses[id]
  if (!proc) return { ok: false }
  proc.stdin.write(command + '\n')
  return { ok: true }
})

ipcMain.handle('get-running-servers', () => Object.keys(serverProcesses))

// ── Dependency check ─────────────────────────────────────────────────────────
ipcMain.handle('check-dependencies', async () => {
  const javaCmd = await findJava()
  let javaVersion = null
  if (javaCmd) {
    javaVersion = await new Promise(res => {
      execFile(javaCmd, ['-version'], (err, stdout, stderr) => {
        const out = (stderr || stdout || '').trim()
        const m = out.match(/version "([^"]+)"/)
        res(m ? m[1] : 'instalado')
      })
    })
  }
  const majorVersion = javaVersion ? parseInt(javaVersion.split('.')[0]) : 0
  const javaOk = javaCmd !== null && majorVersion >= 17
  return {
    java: { ok: javaOk, version: javaVersion, cmd: javaCmd },
  }
})

ipcMain.handle('open-external', (_, url) => shell.openExternal(url))

async function findJava() {
  const candidates = [
    'java',
    '/usr/bin/java',
    '/usr/local/bin/java',
    process.env.JAVA_HOME ? path.join(process.env.JAVA_HOME, 'bin', 'java') : null,
    readConfig().javaPath || null,
  ].filter(Boolean)
  for (const cmd of candidates) {
    try {
      await new Promise((res, rej) => execFile(cmd, ['-version'], err => err ? rej() : res()))
      return cmd
    } catch {}
  }
  return null
}

// ── Servers ───────────────────────────────────────────────────────────────────
ipcMain.handle('get-servers', () => readServers())

ipcMain.handle('delete-server', (_, id) => {
  writeServers(readServers().filter(s => s.id !== id))
  const dir = path.join(SERVERS_DIR, id)
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true })
  return { ok: true }
})

// ── Plugins ───────────────────────────────────────────────────────────────────
ipcMain.handle('search-plugins', async (_, { query, loader }) => {
  const facets = loader === 'fabric'
    ? `[["categories:fabric"],["project_type:mod"]]`
    : `[["categories:paper"],["project_type:plugin"]]`
  const url = `https://api.modrinth.com/v2/search?query=${encodeURIComponent(query)}&facets=${encodeURIComponent(facets)}&limit=20`
  const data = await fetchJson(url)
  return data.hits || []
})

ipcMain.handle('install-plugin', async (event, { serverId, projectId, projectTitle }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false, error: 'Servidor não encontrado' }
  const versions = await fetchJson(`https://api.modrinth.com/v2/project/${projectId}/version`)
  const compatible = versions.find(v =>
    v.loaders.includes(server.type === 'fabric' ? 'fabric' : 'paper') ||
    v.loaders.includes('bukkit') || v.loaders.includes('spigot')
  )
  if (!compatible?.files?.[0]) return { ok: false, error: 'Versão compatível não encontrada' }
  const file = compatible.files[0]
  event.sender.send('create-progress', { id: serverId, msg: `Instalando ${projectTitle}...` })
  await downloadFile(file.url, path.join(server.dir, 'plugins', file.filename))
  return { ok: true, filename: file.filename }
})

ipcMain.handle('get-installed-plugins', (_, serverId) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return []
  const dir = path.join(server.dir, 'plugins')
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir).filter(f => f.endsWith('.jar'))
})

ipcMain.handle('remove-plugin', (_, { serverId, filename }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false }
  const f = path.join(server.dir, 'plugins', filename)
  if (fs.existsSync(f)) fs.unlinkSync(f)
  return { ok: true }
})

// ── playit.gg ─────────────────────────────────────────────────────────────────
ipcMain.handle('toggle-playit', async (event, { serverId, enable }) => {
  if (!enable) {
    const proc = playitProcesses[serverId]
    if (proc) { proc.kill(); delete playitProcesses[serverId] }
    return { ok: true }
  }
  if (!fs.existsSync(PLAYIT_BIN)) {
    event.sender.send('create-progress', { id: serverId, msg: 'Baixando playit.gg...' })
    const arch = process.arch === 'arm64' ? 'aarch64' : 'x86_64'
    const urls = {
      darwin: `https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-darwin-${arch}`,
      win32:  `https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-windows-${arch}.exe`,
      linux:  `https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-${arch}`,
    }
    await downloadFile(urls[process.platform] || urls.linux, PLAYIT_BIN)
    if (process.platform !== 'win32') fs.chmodSync(PLAYIT_BIN, 0o755)
  }
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false }

  const proc = spawn(PLAYIT_BIN, [], { cwd: server.dir, stdio: ['ignore', 'pipe', 'pipe'] })
  playitProcesses[serverId] = proc

  proc.stdout.on('data', d => {
    const text = d.toString()
    const match = text.match(/address[:\s]+([^\s]+:\d+)/i) || text.match(/([\w.-]+\.playit\.gg[:\d]*)/i)
    if (match) event.sender.send('playit-address', { serverId, address: match[1] })
    event.sender.send('playit-log', { serverId, line: text })
  })
  proc.stderr.on('data', d => event.sender.send('playit-log', { serverId, line: d.toString() }))
  proc.on('close', () => { delete playitProcesses[serverId]; event.sender.send('playit-stopped', { serverId }) })

  const idx = servers.findIndex(s => s.id === serverId)
  if (idx !== -1) { servers[idx].playit = true; writeServers(servers) }
  return { ok: true }
})

// ── Auto-update ───────────────────────────────────────────────────────────────
ipcMain.handle('check-update', async (_, { serverId }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server || !['paper', 'purpur'].includes(server.type)) return { hasUpdate: false }
  try {
    let latest
    if (server.type === 'paper') {
      const d = await fetchJson('https://api.papermc.io/v2/projects/paper')
      latest = d.versions[d.versions.length - 1]
    } else {
      const d = await fetchJson('https://api.purpurmc.org/v2/purpur')
      latest = d.versions[d.versions.length - 1]
    }
    return latest && latest !== server.version
      ? { hasUpdate: true, currentVersion: server.version, latestVersion: latest }
      : { hasUpdate: false }
  } catch { return { hasUpdate: false } }
})

ipcMain.handle('update-server', async (event, { serverId }) => {
  const servers = readServers()
  const server = servers.find(s => s.id === serverId)
  if (!server) return { ok: false }
  const send = msg => event.sender.send('create-progress', { id: serverId, msg })
  try {
    let latest
    if (server.type === 'paper') {
      const d = await fetchJson('https://api.papermc.io/v2/projects/paper')
      latest = d.versions[d.versions.length - 1]
    } else if (server.type === 'purpur') {
      const d = await fetchJson('https://api.purpurmc.org/v2/purpur')
      latest = d.versions[d.versions.length - 1]
    }
    if (!latest) return { ok: false, error: 'Versão mais recente não encontrada' }
    send(`Baixando ${server.type} ${latest}...`)
    const jarPath = path.join(server.dir, 'server.jar')
    if (fs.existsSync(jarPath)) fs.renameSync(jarPath, jarPath + '.bak')
    const url = await getJarUrl(server.type, latest)
    await downloadFile(url, jarPath, pct => send(`Download: ${pct}%`))
    const idx = servers.findIndex(s => s.id === serverId)
    servers[idx].version = latest
    writeServers(servers)
    send(`Atualizado para ${latest}!`)
    return { ok: true, newVersion: latest }
  } catch (e) { return { ok: false, error: e.message } }
})

// ── Config & misc ─────────────────────────────────────────────────────────────
ipcMain.handle('get-config', () => readConfig())
ipcMain.handle('set-config', (_, cfg) => { writeConfig({ ...readConfig(), ...cfg }); return { ok: true } })
ipcMain.handle('open-server-folder', (_, serverId) => {
  const s = readServers().find(s => s.id === serverId)
  if (s) shell.openPath(s.dir)
})

// ── Window ────────────────────────────────────────────────────────────────────
function createWindow() {
  const win = new BrowserWindow({
    width: 1200, height: 780, minWidth: 900, minHeight: 620,
    titleBarStyle: 'hiddenInset',
    backgroundColor: '#080d18',
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  })
  if (isDev) { win.loadURL('http://localhost:5173'); win.webContents.openDevTools() }
  else win.loadFile(path.join(__dirname, '../dist/index.html'))
}

app.whenReady().then(createWindow)
app.on('window-all-closed', () => {
  Object.values(serverProcesses).forEach(p => p.kill())
  Object.values(playitProcesses).forEach(p => p.kill())
  if (process.platform !== 'darwin') app.quit()
})
app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow() })
