import type { Server, Plugin } from './types'

export const DEMO_SERVERS: Server[] = [
  {
    id: 'demo-1',
    name: 'Survival da Galera',
    type: 'paper',
    version: '1.21.4',
    ram: 2048,
    port: 25565,
    dir: '/demo',
    createdAt: Date.now() - 86400000 * 3,
    playit: true,
  },
  {
    id: 'demo-2',
    name: 'SkyWars Arena',
    type: 'paper',
    version: '1.21.4',
    ram: 1024,
    port: 25566,
    dir: '/demo2',
    createdAt: Date.now() - 86400000,
    playit: false,
  },
]

export const DEMO_PLUGINS: Plugin[] = [
  { project_id: 'essentialsx', slug: 'essentialsx', title: 'EssentialsX', description: 'O plugin essencial para qualquer servidor — comandos /home, /tp, /spawn, /kit e muito mais.', icon_url: null, downloads: 12_400_000, categories: ['utility'], source: 'modrinth' },
  { project_id: 'luckperms', slug: 'luckperms', title: 'LuckPerms', description: 'Sistema de permissões moderno e poderoso. Crie grupos, defina permissões e gerencie players.', icon_url: null, downloads: 9_800_000, categories: ['admin-tools'], source: 'modrinth' },
  { project_id: 'worldedit', slug: 'worldedit', title: 'WorldEdit', description: 'Edite mundos gigantes em segundos com seleções, pincel e comandos de construção.', icon_url: null, downloads: 8_200_000, categories: ['world-management'], source: 'modrinth' },
  { project_id: 'worldguard', slug: 'worldguard', title: 'WorldGuard', description: 'Proteja regiões, bloqueie danos e controle permissões por área.', icon_url: null, downloads: 6_900_000, categories: ['world-management'], source: 'modrinth' },
  { project_id: 'vault', slug: 'vault', title: 'Vault', description: 'API de economia e permissões usada por centenas de outros plugins.', icon_url: null, downloads: 5_600_000, categories: ['library'], source: 'modrinth' },
  { project_id: 'placeholderapi', slug: 'placeholderapi', title: 'PlaceholderAPI', description: 'Crie placeholders dinâmicos para usar em outros plugins — nome do player, rank, etc.', icon_url: null, downloads: 4_200_000, categories: ['library'], source: 'modrinth' },
  { project_id: 'coreprotect', slug: 'coreprotect', title: 'CoreProtect', description: 'Registra todas as ações no servidor. Reverta griefs e veja quem quebrou o que.', icon_url: null, downloads: 3_800_000, categories: ['admin-tools'], source: 'modrinth' },
  { project_id: 'viaversion', slug: 'viaversion', title: 'ViaVersion', description: 'Deixa jogadores de versões mais novas entrarem no seu servidor.', icon_url: null, downloads: 7_100_000, categories: ['library'], source: 'modrinth' },
  { project_id: 'spark', slug: 'spark', title: 'spark', description: 'Profiler de performance para identificar lag e gargalos em tempo real.', icon_url: null, downloads: 2_300_000, categories: ['admin-tools'], source: 'modrinth' },
  { project_id: 'chunky', slug: 'chunky', title: 'Chunky', description: 'Pré-gera chunks do mapa em background. Zero lag de terreno para novos jogadores.', icon_url: null, downloads: 1_900_000, categories: ['optimization'], source: 'modrinth' },
  { project_id: 'decentholograms', slug: 'decentholograms', title: 'DecentHolograms', description: 'Crie hologramas flutuantes com texto, itens e animações.', icon_url: null, downloads: 1_500_000, categories: ['decoration'], source: 'hangar' },
  { project_id: 'authme', slug: 'authme', title: 'AuthMe', description: 'Sistema de login/registro para servidores offline. Seguro e configurável.', icon_url: null, downloads: 1_200_000, categories: ['authentication'], source: 'modrinth' },
]

export const DEMO_INSTALLED = ['EssentialsX-2.21.0.jar', 'LuckPerms-5.4.141.jar', 'spark-1.10.jar']

// Real Minecraft log strings — they go through translateLog for translation
export const DEMO_LOGS: { delay: number; text: string }[] = [
  { delay: 0,    text: '[12:00:00] [Server thread/INFO]: Starting Minecraft server on *:25565' },
  { delay: 600,  text: '[12:00:00] [Server thread/INFO]: Loading properties' },
  { delay: 900,  text: '[12:00:01] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld' },
  { delay: 1200, text: '[12:00:01] [Server thread/INFO]: Preparing spawn area: 0%' },
  { delay: 1500, text: '[12:00:01] [Server thread/INFO]: Preparing spawn area: 48%' },
  { delay: 1800, text: '[12:00:01] [Server thread/INFO]: Preparing spawn area: 83%' },
  { delay: 2200, text: '[12:00:02] [Server thread/INFO]: [Server thread/INFO]: Enabling EssentialsX v2.21.0' },
  { delay: 2500, text: '[12:00:02] [Server thread/INFO]: [Server thread/INFO]: Enabling LuckPerms v5.4.141' },
  { delay: 2800, text: '[12:00:03] [Server thread/INFO]: LuckPerms v5.4.141 loaded successfully' },
  { delay: 3200, text: '[12:00:03] [Server thread/INFO]: Done (3.212s)! For help, type "help"' },
  { delay: 4500, text: '[12:00:05] [Server thread/INFO]: UUID of player Steve is a1b2c3d4' },
  { delay: 4800, text: '[12:00:05] [Server thread/INFO]: Steve joined the game' },
  { delay: 5500, text: '[12:00:06] [Server thread/INFO]: <Steve> oi pessoal, servidor tá ótimo!' },
  { delay: 6500, text: '[12:00:07] [Server thread/INFO]: UUID of player Alex is b2c3d4e5' },
  { delay: 6800, text: '[12:00:07] [Server thread/INFO]: Alex joined the game' },
  { delay: 7500, text: '[12:00:08] [Server thread/INFO]: <Alex> bom dia!!' },
  { delay: 8200, text: '[12:00:09] [Server thread/INFO]: Steve issued server command: /gamemode creative' },
  { delay: 8500, text: '[12:00:09] [Server thread/INFO]: Set Steve\'s game mode to Creative Mode' },
  { delay: 9500, text: '[12:00:10] [Server thread/INFO]: Made Alex a server operator' },
  { delay: 10500, text: '[12:00:11] [Server thread/INFO]: Teleported Steve to Alex' },
  { delay: 11500, text: '[12:00:12] [Server thread/INFO]: <Steve> vem ver esse lugar aqui' },
  { delay: 12500, text: '[12:00:13] [Server thread/INFO]: Set the time to 6000' },
  { delay: 13500, text: '[12:00:14] [Server thread/INFO]: Set the weather to clear for 600 seconds' },
  { delay: 14500, text: '[12:00:15] [Server thread/INFO]: Alex has made the advancement [Stone Age]' },
  { delay: 15500, text: '[12:00:16] [Server thread/INFO]: Saving the game' },
  { delay: 16000, text: '[12:00:16] [Server thread/INFO]: Saved the game' },
  { delay: 17500, text: '[12:00:17] [Server thread/INFO]: <Alex> quanto players cabem?' },
  { delay: 18200, text: '[12:00:18] [Server thread/INFO]: There are 2 of a max of 20 players online: Steve, Alex' },
  { delay: 19500, text: '[12:00:19] [Server thread/INFO]: Steve issued server command: /give Alex diamond 64' },
  { delay: 19800, text: '[12:00:19] [Server thread/INFO]: Gave 64 [Diamond] to Alex' },
  { delay: 21000, text: '[12:00:21] [Server thread/INFO]: Alex was slain by Zombie' },
  { delay: 22000, text: '[12:00:22] [Server thread/INFO]: <Steve> kkkkk cuidado!' },
  { delay: 23000, text: '[12:00:23] [Server thread/INFO]: Alex issued server command: /tp Steve' },
  { delay: 23300, text: '[12:00:23] [Server thread/INFO]: Teleported Alex to Steve' },
]
